# Generated by Django 5.2.17 on 2026-08-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_payment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['lsa', 'booking_date'], name='booking_lsa_date_idx'),
        ),
    ]
